server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  config:
    import: "optional:configserver:http://localhost:8071"
  profiles:
    active: "qa"
  application:
    name: "cards"

management:
  endpoints:
    web:
      exposure:
        include: "*"

    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true

  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true


  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Cards Service of Microservice tutorial"
    version: "1.0.0"

logging:
  level:
    com:
      eazybites:
        cards: "DEBUG"