spring:
  application:
    name: "config server"
  profiles:
#    active: "native"
    active: "git"

  cloud:
    config:
      server:
#        native:
        git:
#          search-locations: "classpath:/config"
#          search-locations: "file:///C://Users//CBT//Documents//config"
          uri: "https://github.com/Ashraf20001/spring-cloud-config-repo.git"
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 5

encrypt:
  key: "YCTPW98E7R32HTFP98WMXP87PCYLKJYFNQ2T"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        includes: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


logging:
  level:
    com:
      microservice:
        config: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
