spring:
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071"
  application:
    name: "loans"
  profiles:
    active: "qa"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"