spring:
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
  application:
    name: "loans"
  profiles:
    active: "qa"

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"