server:
    port: 8080
    
spring:
    datasource:
       url: jdbc:mysql://localhost:3307/accountsdb
       username: root
       password: root
    jpa:
    sql:
      init:
        mode: always
      show-sql: true

    application:
      name: "accounts"
    config:
      import: "optional:configserver:http://localhost:8071"
    profiles:
      active: "qa"

management:
  endpoints:
    web:
      exposure:
        include: "*"
               