services:
  accountsdb:
    container_name: "accountsdb"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "accountsdb"
    extends:
      file: common-config.yml
      service: mysql_db_config_service
  loansdb:
    container_name: "loansdb"
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "loansdb"
    extends:
      file: common-config.yml
      service: mysql_db_config_service

  cardsdb:
    container_name: "cardsdb"
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: "cardsdb"
    extends:
      file: common-config.yml
      service: mysql_db_config_service


  config:
    image: "ashraf2001/config:mcconfigs7"
    container_name: "ashraf_config"
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "ashraf2001/accounts:mcaccountss7"
    container_name: "ashraf_acc"
    ports:
      - "8080:8080"
    depends_on:
      config:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-base-config

  cards:
    image: "ashraf2001/cards:mcccardss7"
    container_name: "ashraf_card"
    ports:
      - "9000:9000"
    depends_on:
      config:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-base-config


  loans:
    image: "ashraf2001/loans:mcloanss7"
    container_name: "ashraf_loan"
    ports:
      - "8090:8090"
    depends_on:
      config:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-base-config

networks:
  microservice:
    driver: "bridge"
