services:
  network-deploy-service:
    networks:
      - "microservice"
  microservice-base-config:
    extends:
      network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
  microservice-configserver-base-config:
    extends:
      microservice-base-config
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config:8071/"
      SPRING_PROFILES_ACTIVE: "prod"